Language School Web/Controllers/ClassesController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using LanguageSchool.Models;
using Microsoft.Win32;
using SelectPdf;

namespace Language_School_Web.Controllers
{
    public class ClassesController : Controller
    {
        // GET: Classes
        public ActionResult Index()
        {
            IEnumerable<ClassDataDto> allClasses = null;
            IEnumerable<ClassBasicDataDto> topClasses = null;
            IEnumerable<ClassBasicDataDto> suggestedClasses = null;
            IEnumerable<ClassBasicDataDto> studentClasses = null;
            bool isLoggedInUser = false;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://projektnet.mini.pw.edu.pl/LanguageSchoolWeb/api/");
                var responseTask = client.GetAsync("classes");
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<ClassDataDto>>();
                    readTask.Wait();

                    allClasses = readTask.Result;
                }
                else
                    return View("~/Views/Shared/Error.cshtml");

                responseTask = client.GetAsync("classes/top/3");
                responseTask.Wait();

                result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<ClassBasicDataDto>>();
                    readTask.Wait();
                    topClasses = readTask.Result;
                }
                else
                    return View("~/Views/Shared/Error.cshtml");

                HttpCookie cookie = Request.Cookies["token"];
                if (cookie != null)
                {
                    string accessToken = cookie.Value;
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

                    responseTask = client.GetAsync("classes/suggested");
                    responseTask.Wait();

                    result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsAsync<IList<ClassBasicDataDto>>();
                        readTask.Wait();

                        suggestedClasses = readTask.Result;
                    }
                    else
                        return View("~/Views/Shared/Error.cshtml");

                    responseTask = client.GetAsync("student/classes");
                    responseTask.Wait();

                    result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsAsync<IList<ClassBasicDataDto>>();
                        readTask.Wait();

                        studentClasses = readTask.Result;
                    }
                    else
                        return View("~/Views/Shared/Error.cshtml");

                    var studentClassesIds = studentClasses.Select(c => c.Id);
                    allClasses = allClasses.Where(c => !studentClassesIds.Contains(c.Id));
                    isLoggedInUser = true;
                }
            }
            return View(Tuple.Create(allClasses, topClasses, suggestedClasses, isLoggedInUser));
        }

        public ActionResult Schedule()
        {
            IEnumerable<ClassDataDto> userClasses = null;
            IEnumerable<ScheduleDay> scheduleDays = null;
            HttpCookie cookie = Request.Cookies["token"];
            if (cookie != null)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("http://projektnet.mini.pw.edu.pl/LanguageSchoolWeb/api/");
                    string accessToken = cookie.Value;
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

                    var responseTask = client.GetAsync("student/classes");
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsAsync<IList<ClassDataDto>>();
                        readTask.Wait();

                        userClasses = readTask.Result;
                        scheduleDays = userClasses.GroupBy(c => c.DayOfWeek)
                            .Select(group => new ScheduleDay() { Day = group.Key, Items = group.ToList() });
                    }
                    else
                        return View("~/Views/Shared/Error.cshtml");
                }

                return View(scheduleDays);
            }
            else
                return RedirectToAction("ScheduleView");
        }

        public ActionResult SignFor(int classId)
        {
            HttpCookie cookie = Request.Cookies["token"];
            if (cookie != null)
            {
                string accessToken = cookie.Value;
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("http://projektnet.mini.pw.edu.pl/LanguageSchoolWeb/api/");
                    accessToken = cookie.Value;
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

                    var postTask = client.PostAsync("classes/" + classId.ToString(), null);
                    postTask.Wait();

                    var result = postTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                }
                return Index();
            }
            else
                return View("~/Views/Shared/AccessDenied.cshtml");
        }

        public ActionResult GetPdf()
        {
            HttpCookie cookie = Request.Cookies["token"];
            if (cookie != null)
            {
                string accessToken = cookie.Value;
                HtmlToPdf converter = new HtmlToPdf();
                converter.Options.HttpCookies.Add("token", accessToken);
                converter.Options.PdfPageSize = PdfPageSize.A4;
                converter.Options.PdfPageOrientation = PdfPageOrientation.Landscape;
                converter.Options.MarginLeft = 0;
                converter.Options.MarginRight = 0;
                converter.Options.MarginTop = 0;
                converter.Options.MarginBottom = 0;
                PdfDocument doc = converter.ConvertUrl("http://localhost:53091/Classes/Schedule");
                DateTime now = DateTime.Now;
                string fileName = "/Schedule" + now.Year.ToString() + now.Month.ToString() + now.Day.ToString() + now.Hour.ToString() + now.Minute.ToString() + now.Second.ToString() + ".pdf";
                doc.Save(getDownloadFolderPath() + fileName);
                doc.Close();
                return RedirectToAction("ScheduleView");
            }
            else
                return View("~/Views/Shared/AccessDenied.cshtml");
        }

        public ActionResult ScheduleView()
        {
            HttpCookie cookie = Request.Cookies["token"];
            if (cookie != null)
                return View();
            else
                return View("~/Views/Shared/AccessDenied.cshtml");
        }

        string getDownloadFolderPath()
        {
            return Registry.GetValue(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders", "{374DE290-123F-4565-9164-39C4925E467B}", String.Empty).ToString();
        }
    }
}

Language School Web/Controllers/HomeController.cs
using LanguageSchool.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;

namespace Language_School_Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            StudentDataDto model = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://projektnet.mini.pw.edu.pl/LanguageSchoolWeb/api/");
                HttpCookie cookie = Request.Cookies["token"];
                if (cookie != null)
                {
                    string accessToken = cookie.Value;
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                    //HTTP GET
                    var responseTask = client.GetAsync("student/info");
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsAsync<StudentDataDto>();
                        readTask.Wait();

                        model = readTask.Result;
                    }
                    else //web api sent error response 
                    {
                        //log response status here..

                        model = new StudentDataDto();

                        ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                    }
                }
            }
            return View(model);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View("~/Views/Home/Contact.cshtml");
        }

        
    }
}

Language School Web/Views/Home/About.cshtml
@{
    Layout = null;
}
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Language School Web/Views/Home/Index.cshtml
@model LanguageSchool.Models.StudentDataDto

@{
    ViewBag.Title = "Home Page";
}

<div class="row mt-5">
    <div class="col-md-6">
        <img class="card-img-top img-fluid w-100 m-3" src="https://blog.apaonline.org/wp-content/uploads/2016/09/hello-in-foreign-languages.png" alt="">
    </div>
    <div class="col-md-6">
        <div class="m-5">
            @if (Model == null)
            {
            <h1 class="ml-5">New to Language School?</h1>
            <ul class="navbar-nav ml-5 mt-3">
                <li>
                    <h5 class="text-secondary">
                        <i class="fa fa-chevron-right text-primary"></i>
                        Check our <a href="@Url.Action("Index", "Classes")">offer</a>
                    </h5>
                </li>
                <li>
                    <h5 class="text-secondary">
                        <i class="fa fa-chevron-right text-primary"></i>
                        Questions? <a href="@Url.Action("Contact", "Home")">Contact</a> us
                    </h5>
                </li>
                <li>
                    <h5 class="text-secondary">
                        <i class="fa fa-chevron-right text-primary"></i>
                        Wanna join us? <a href="@Url.Action("Register", "Account")">Sign up!</a>
                    </h5>
                </li>
            </ul>
            }
            else
            {
            <h1 class="ml-5">Hello @Html.DisplayFor(modelItem => Model.FirstName)!</h1>
            <ul class="navbar-nav ml-5 mt-3">
                <li>
                    <h5 class="text-secondary">
                        <i class="fa fa-chevron-right text-primary"></i>
                        Check suggestions and new classses in our offer
                    </h5>
                </li>
                <li>
                    <h5 class="text-secondary">
                        <i class="fa fa-chevron-right text-primary"></i>
                        Manage your classes
                    </h5>
                </li>
                <li>
                    <h5 class="text-secondary">
                        <i class="fa fa-chevron-right text-primary"></i>
                        Meet your classmates
                    </h5>
                </li>
                <li>
                    <h5 class="text-secondary">
                        <i class="fa fa-chevron-right text-primary"></i>
                        Learn foreign languages with us
                    </h5>
                </li>
            </ul>
            }
        </div>
    </div>
</div>